### ISSUE TITLE
Unexpected Error Logging Despite Handled Exceptions

### ISSUE THREAD

**Issue by diegomais** [workos/authkit-js#52]
Hello,

I'm encountering an issue with the `@workos-inc/authkit-js` library where it logs errors to the browser console even though the errors are expected.

![image](https://github.com/user-attachments/assets/3cce6b9c-85f7-4b76-b46d-7b12c9ce2ce7)

Specifically, in the code snippet:

https://github.com/workos/authkit-js/blob/5efd97fa980cc33b548171b91049124883e94f98/src/create-client.ts#L108

```typescript
  async initialize() {
    // [...]
      try {
        await this.#refreshSession();
        this.#scheduleAutomaticRefresh();
      } catch {
        // this is expected to fail if a user doesn't
        // have a session. do nothing.
      }
    }
  }
```
It seems like errors are being logged despite the comment indicating that the failure to refresh a session is expected and should be silently ignored. Could you please look into this behavior? It would be great to see the error logging suppressed here unless there's a real issue to address.

Thank you!

**Comment by diegomais** [comment]
Additionally, I've noticed that even without a refresh token, the method `authenticateWithRefreshToken()` is called, resulting in unnecessary HTTP requests. This behavior seems inefficient and could potentially be avoided if there's no refresh token available.

https://github.com/workos/authkit-js/blob/5efd97fa980cc33b548171b91049124883e94f98/src/create-client.ts#L278C46-L278C74

Could you please also look into this behavior? Optimizing the process to prevent unnecessary requests would be appreciated.

**Comment by paulfalgout** [comment]
Similarly we're getting hammered with console errors:
`Error: Missing refresh token.`
`Error: Session has already ended.`
`Error: Session has already ended.`
But it doesn't seem like there's anything to do to fix these errors, nor that there's any way to supress them.

**Comment by arnabk** [comment]
@cmatheson We are continuing to see the same error.
![image](https://github.com/user-attachments/assets/40c2dfd1-6746-4f8a-a1fa-e1f8782a3655)

This is our version
```
"@workos-inc/authkit-react": "^0.7.0",
```

Should I open a new defect?

**Comment by paulfalgout** [comment]
This commit wasn't added until 0.7.1 but it wasn't mentioned in the release notes: https://github.com/workos/authkit-js/compare/v0.7.0...v0.7.1

**Comment by bharat2913** [comment]
@cmatheson  even after upgrading to latest version, we are continuing to see the same error.

![image](https://github.com/user-attachments/assets/ae2161ce-139a-4db9-bdac-7725fda77b86)

any update on this?

**Comment by bharat2913** [comment]
@cmatheson we're continuing to see the same error. Do we have any update coming for this?

<img width="1077" alt="Image" src="https://github.com/user-attachments/assets/d9d2b857-9e59-4471-bdc8-3f13ef9b9448" />


This is our version

```
"@workos-inc/authkit-react": "^0.9.0" 
```

Should I create a new issue?
